// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var Comment;
    return Comment = sequelize.define('Comment', {
      _id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
      },
      content: DataTypes.STRING,
      active: DataTypes.BOOLEAN,
      post_time: {
        type: DataTypes.TIME
      },
      like_count: {
        type: DataTypes.INTEGER
      }
    });
  };

}).call(this);

//# sourceMappingURL=comment.model.js.map
